name: Node.js CI

on:
  push:
    branches: [ test ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [17.x]

    steps:
      - uses: actions/checkout@v3  # Оновлена версія checkout
      
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3  # Оновлена версія setup-node
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'  # Кешування залежностей

      - run: npm ci --legacy-peer-deps
      - run: npm run build --if-present